version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.13.3
    working_directory: /go/src/github.com/shibataka000/daily-report
    steps:
      - checkout
      - run:
          name: Setup
          command: make setup
      - run:
          name: Run tests
          command: make ci
